/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pt.pak3nuh.util.logviewer

import pt.pak3nuh.util.logviewer.view.MainView
import tornadofx.*

class LogViewerApp : App(MainView::class)

fun main(args: Array<String>) {
    launch<LogViewerApp>(args)
}
